### PR TITLE
Test refactoring(new)

### PR DESCRIPTION
**Pull request by Danx1129**
Added Test Classes, refactored Classes, and Added Documentation 
## Your Changes

**Description**:
Added Test Classes and Documentation for, and refactored LoansScoreCalculator, LoanResponseConstructor, Updates BasicLoanTest 

**Type of change** (select all that apply):

- [ ] New feature (additional functionality separate from existing code)
- [X] Refactoring (changing code structure only)
- [ ] Breaking change (changing code functionality)
- [X] Documentation update (adding more comments)
- [ ] Bug fix (non-breaking change that solves an error/issue)
- [ ] User Interface change (design changes)
- [X] Test update (adding test code)
- [ ] Other (please specify):

## Testing

Completed and passed the Test Classes

## Notes

BackEnd all DONE!

## Checklist

- [ ] Code is up to date with main branch (no merge conflicts)
- [X] Code has been properly tested
- [X] Code has been properly documented
- [ ] One or two people have reviewed this pull request

### CODE REVIEW

**Review by elizabethhli — COMMENTED** [review]
In the javadocs, for example for LoansScoreCalculator, write separate docs for each of the getter methods and a small thing - be consistent with capitalizing the java docs. There's some that start with lowercase and some with uppercase. Opt for upper case. In general, avoid explaining how the method works and instead what it does. For example in LoanResponseConstructor, instead of documenting generateScore as "Loops through each Loan in BasicLoan and calls createInfo", you could instead write "Generates score based on the User and their 3 possible loans"
In BasicLoansTest, can we remove any unnecessary commented out code

**Review by jiah29 — CHANGES_REQUESTED** [review]
For loanscorecalculatortest, it would be better if you could just put the assert statements into separate test cases, but that is not a huge issue. Elizabeth has pointed some more important changes that need to be made

**Review by jiah29 — APPROVED** [review]
Everything looks good

**Review by elizabethhli — APPROVED** [review]
Everything looks good!

**Review by jiah29 — APPROVED** [review]
Everything looks good!

**Comment by Sophieeeeeeeee** [comment]
Looks good!

**Comment by Sophieeeeeeeee** [comment]
Looks good!

**Comment by Sophieeeeeeeee** [comment]
Looks good!

**Pull request merged**
